version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - eval $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=560360184571.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_REPO_NAME=alpine
      - IMAGE_TAG=1.1
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo $REPOSITORY_URI/$IMAGE_REPO_NAME:$IMAGE_TAG > example.json
artifacts:
    files: example.json

